Repository Enterprise-CMCS/macpro-mdct-qmr, pull requests merged in 2023-07, with the labels that each got.

#1864 LSC-CH Hybrid Text
  services/ui-src/src/measures/2023/LSCCH/index.tsx
Labels: ready for review

#1863 update REDIRECT_SIGNOUT based on env
  .env_example
  services/ui-auth/serverless.yml
  services/ui-src/serverless.yml
  services/ui-src/src/hooks/authHooks/userProvider.tsx
Labels: ready for review, product review

#1867 HH Qualifier - Individual Total
  services/ui-src/src/components/Inputs/NumberInput/index.tsx
  services/ui-src/src/measures/2023/shared/Qualifiers/Common/administrativeQuestions.test.tsx
  services/ui-src/src/measures/2023/shared/Qualifiers/Common/administrativeQuestions.tsx
Labels: ready for review

#1881 Associate OMS qualifiers with PM qualifiers by ID
  services/ui-src/src/measures/2023/shared/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
Labels: ready to merge

#1879 APM-CH/WCCCH - Validation Error
  services/ui-src/src/measures/2023/shared/globalValidations/validateTotals/index.ts
Labels: ready to merge

#1878 [MDCT-2416] default scan to iterate across results
  services/app-api/handlers/kafka/get/forceKafkaSync.js
  services/app-api/handlers/measures/get.ts
  services/app-api/libs/dynamodb-lib.ts
  services/app-api/libs/tests/dynamodb-lib.test.ts
  services/app-api/types.ts
Labels: ready to merge

#1892 Unit Test for Cross Category Calculation
  services/ui-src/src/components/IETRate/index.test.tsx
Labels: ready for review

#1897 Removing Text in Additional Notes on Reporting Change
  services/ui-src/src/measures/2023/shared/CommonQuestions/AdditionalNotes/index.test.tsx
  services/ui-src/src/measures/2023/shared/CommonQuestions/AdditionalNotes/index.tsx
Labels: ready for review

#1902 Date Range Enhancements
  services/ui-src/src/components/Inputs/RadioButton/index.tsx
  services/ui-src/src/components/MonthPicker/calendarPopup.tsx
  services/ui-src/src/measures/2023/shared/CommonQuestions/DateRange/index.tsx
Labels: ready for review, product review
