Repository Enterprise-CMCS/macpro-mdct-qmr, pull requests merged in 2023-06, with the labels that each got.

#1820 OMS Rate Order Changes Global
  services/ui-src/src/measures/2023/AMMAD/validation.ts
  services/ui-src/src/measures/2023/IETAD/validation.ts
  services/ui-src/src/measures/2023/IETHH/validation.ts
  services/ui-src/src/measures/2023/shared/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
  services/ui-src/src/measures/2023/shared/CommonQuestions/OptionalMeasureStrat/omsNodeBuilder.tsx
  services/ui-src/src/measures/2023/shared/CommonQuestions/OptionalMeasureStrat/omsUtil.tsx
  services/ui-src/src/measures/2023/shared/CommonQuestions/types.ts
  services/ui-src/src/measures/2023/shared/globalValidations/dataDrivenTools.ts
  services/ui-src/src/measures/2023/shared/globalValidations/index.ts
  services/ui-src/src/measures/2023/shared/globalValidations/omsValidator/index.ts
  services/ui-src/src/measures/2023/shared/globalValidations/validateSameDenominatorSets/index.test.ts
  services/ui-src/src/measures/2023/shared/globalValidations/validateSameDenominatorSets/index.ts
  services/ui-src/src/measures/2023/shared/globalValidations/validateTotals/index.ts
  services/ui-src/src/utils/testUtils/2023/validationHelper.test.ts
  services/ui-src/src/utils/testUtils/2023/validationHelpers.ts
Labels: ready for review

#1825 Removed Hedis Validation From Non Hedis Measures
  services/ui-src/src/measures/2023/CPAAD/validation.ts
  services/ui-src/src/measures/2023/CPCCH/validation.ts
  services/ui-src/src/measures/2023/HPCMIAD/validation.ts
  services/ui-src/src/measures/2023/IUHH/validation.ts
  services/ui-src/src/measures/2023/SSDAD/validation.ts
  services/ui-src/src/measures/2023/W30CH/validation.ts
  services/ui-src/src/measures/2023/WCCCH/validation.ts
  services/ui-src/src/measures/2023/WCVCH/validation.ts
Labels: ready for review

#1827 Content Changes to HH - SPA replacement
  services/ui-src/src/measures/2023/shared/CommonQuestions/CombinedRates/index.test.tsx
  services/ui-src/src/measures/2023/shared/CommonQuestions/CombinedRates/index.tsx
Labels: ready for review

#1829 Combined Rates Validation Flag
  services/ui-src/src/measures/2023/AABCH/index.test.tsx
  services/ui-src/src/measures/2023/AABCH/validation.ts
Labels: ready for review

#1834 Add missing validation for CPU-AD
  services/ui-src/src/measures/2023/CPUAD/index.test.tsx
  services/ui-src/src/measures/2023/CPUAD/validation.ts
Labels: ready for review

#1826 Hedis Validation For Other
  services/ui-src/src/measures/2023/AABAD/validation.ts
  services/ui-src/src/measures/2023/AABCH/validation.ts
  services/ui-src/src/measures/2023/ADDCH/validation.ts
  services/ui-src/src/measures/2023/AMBCH/validation.ts
  services/ui-src/src/measures/2023/AMBHH/validation.ts
  services/ui-src/src/measures/2023/AMMAD/validation.ts
  services/ui-src/src/measures/2023/AMRAD/validation.ts
  services/ui-src/src/measures/2023/AMRCH/validation.ts
  services/ui-src/src/measures/2023/APMCH/validation.ts
  services/ui-src/src/measures/2023/APPCH/validation.ts
  services/ui-src/src/measures/2023/BCSAD/validation.ts
  services/ui-src/src/measures/2023/CBPAD/validation.ts
  services/ui-src/src/measures/2023/CBPHH/validation.ts
  services/ui-src/src/measures/2023/CCSAD/validation.ts
  services/ui-src/src/measures/2023/CHLAD/validation.ts
  services/ui-src/src/measures/2023/CHLCH/validation.ts
  services/ui-src/src/measures/2023/CISCH/validation.ts
  services/ui-src/src/measures/2023/COLAD/validation.ts
  services/ui-src/src/measures/2023/COLHH/validation.ts
  services/ui-src/src/measures/2023/CPUAD/validation.ts
  services/ui-src/src/measures/2023/FUAAD/validation.ts
  services/ui-src/src/measures/2023/FUACH/validation.ts
  services/ui-src/src/measures/2023/FUAHH/validation.ts
  services/ui-src/src/measures/2023/FUHAD/validation.ts
  services/ui-src/src/measures/2023/FUHCH/validation.ts
  services/ui-src/src/measures/2023/FUHHH/validation.ts
  services/ui-src/src/measures/2023/FUMAD/validation.ts
  services/ui-src/src/measures/2023/FUMCH/validation.ts
  services/ui-src/src/measures/2023/FUMHH/validation.ts
  services/ui-src/src/measures/2023/FVAAD/validation.ts
  services/ui-src/src/measures/2023/HBDAD/validation.ts
  services/ui-src/src/measures/2023/IETAD/validation.ts
  services/ui-src/src/measures/2023/IETHH/validation.ts
  services/ui-src/src/measures/2023/IMACH/validation.ts
  services/ui-src/src/measures/2023/LSCCH/validation.ts
  services/ui-src/src/measures/2023/MSCAD/validation.ts
  services/ui-src/src/measures/2023/PCRAD/validation.ts
  services/ui-src/src/measures/2023/PCRHH/validation.ts
  services/ui-src/src/measures/2023/PPCAD/validation.ts
  services/ui-src/src/measures/2023/PPCCH/validation.ts
  services/ui-src/src/measures/2023/SAAAD/validation.ts
  services/ui-src/src/measures/2023/SSDAD/validation.ts
  services/ui-src/src/measures/2023/W30CH/validation.ts
  services/ui-src/src/measures/2023/WCCCH/validation.ts
  services/ui-src/src/measures/2023/WCVCH/validation.ts
  services/ui-src/src/measures/2023/shared/globalValidations/validateHedisYear/index.test.ts
  services/ui-src/src/measures/2023/shared/globalValidations/validateHedisYear/index.ts
Labels: ready for review, product review

#1823 Fix IETRate for IET-HH
  services/ui-src/src/components/IETRate/index.test.tsx
  services/ui-src/src/components/IETRate/index.tsx
Labels: ready for review

#1831 Bug Fix: IU-HH Validation
  services/ui-src/src/measures/2023/shared/globalValidations/ComplexValidations/ComplexValueSameCrossCategory/index.tsx
Labels: ready for review, product review

#1817 MDCT-2337: Non-Required Measurement Fix (SPIKE Output)
  services/ui-src/src/components/MeasureWrapper/index.test.tsx
  services/ui-src/src/components/MeasureWrapper/index.tsx
Labels: ready for review, ready to merge
