Repository Enterprise-CMCS/macpro-mdct-qmr, pull requests merged in 2023-05, with the labels that each got.

#1785 Tech Spec Changes - IET-HH
  services/ui-src/src/measures/2023/IETHH/data.ts
  services/ui-src/src/measures/measureDescriptions.ts
Labels: ready for review

#1793 Update NCIDDS-AD Title
  services/ui-src/src/measures/measureDescriptions.ts
Labels: ready for review

#1788 Tech Spec Changes - Changes to N/D/R Set(s)
  services/ui-src/src/measures/2023/COLHH/data.ts
  services/ui-src/src/measures/2023/rateLabelText.ts
Labels: ready for review, design review

#1789 [QMR] New Measure - AAB-CH
  services/app-api/handlers/dynamoUtils/measureList.ts
  services/ui-src/src/measures/2023/AABCH/data.ts
  services/ui-src/src/measures/2023/AABCH/index.test.tsx
  services/ui-src/src/measures/2023/AABCH/index.tsx
  services/ui-src/src/measures/2023/AABCH/types.ts
  services/ui-src/src/measures/2023/AABCH/validation.ts
  services/ui-src/src/measures/2023/index.tsx
  services/ui-src/src/measures/2023/rateLabelText.ts
  services/ui-src/src/measures/measureDescriptions.ts
Labels: ready for review

#1800 Create new measure: CPU-AD
  services/app-api/handlers/dynamoUtils/measureList.ts
  services/ui-src/src/dataConstants.ts
  services/ui-src/src/measures/2023/CPUAD/data.ts
  services/ui-src/src/measures/2023/CPUAD/index.test.tsx
  services/ui-src/src/measures/2023/CPUAD/index.tsx
  services/ui-src/src/measures/2023/CPUAD/types.ts
  services/ui-src/src/measures/2023/CPUAD/validation.ts
  services/ui-src/src/measures/2023/index.tsx
  services/ui-src/src/measures/2023/rateLabelText.ts
  services/ui-src/src/measures/measureDescriptions.ts
Labels: ready for review, product review

#1794 [QMR] New Measure - LSC-CH
  services/app-api/handlers/dynamoUtils/measureList.ts
  services/ui-src/src/measures/2023/LSCCH/data.ts
  services/ui-src/src/measures/2023/LSCCH/index.test.tsx
  services/ui-src/src/measures/2023/LSCCH/index.tsx
  services/ui-src/src/measures/2023/LSCCH/questions/PerformanceMeasure.tsx
  services/ui-src/src/measures/2023/LSCCH/questions/index.test.tsx
  services/ui-src/src/measures/2023/LSCCH/types.ts
  services/ui-src/src/measures/2023/LSCCH/validation.ts
  services/ui-src/src/measures/2023/index.tsx
  services/ui-src/src/measures/2023/rateLabelText.ts
  services/ui-src/src/measures/measureDescriptions.ts
Labels: ready for review, product review

#1809 Streamline oms
  services/ui-src/src/dataConstants.ts
  services/ui-src/src/measures/2023/AIFHH/validation.ts
  services/ui-src/src/measures/2023/CPUAD/index.tsx
  services/ui-src/src/measures/2023/FVAAD/index.tsx
  services/ui-src/src/measures/2023/IUHH/validation.ts
  services/ui-src/src/measures/2023/MSCAD/index.tsx
  services/ui-src/src/measures/2023/PCRAD/index.tsx
  services/ui-src/src/measures/2023/PCRHH/index.tsx
  services/ui-src/src/measures/2023/rateLabelText.ts
  services/ui-src/src/measures/2023/shared/CommonQuestions/NotCollectingOMS/index.test.tsx
  services/ui-src/src/measures/2023/shared/CommonQuestions/NotCollectingOMS/index.tsx
  services/ui-src/src/measures/2023/shared/CommonQuestions/OptionalMeasureStrat/index.tsx
  services/ui-src/src/measures/2023/shared/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
  services/ui-src/src/measures/2023/shared/CommonQuestions/index.tsx
  services/ui-src/src/measures/2023/shared/CommonQuestions/types.ts
Labels: ready for review

#1814 508 Remediation - Remove Extra Link
  services/ui-src/src/components/Breadcrumbs/index.tsx
Labels: ready for review

#1812 Mdct 2442 oms updates
  services/ui-src/src/measures/2023/shared/CommonQuestions/OptionalMeasureStrat/data.ts
  services/ui-src/src/measures/2023/shared/CommonQuestions/OptionalMeasureStrat/omsNodeBuilder.tsx
  services/ui-src/src/measures/2023/shared/globalValidations/omsValidator/index.test.ts
  tests/cypress/cypress/integration/measures/adult/HBDAD.spec.ts
Labels: ready for review, product review

#1803 IET Total Rates / Validation
  services/ui-src/src/components/IETRate/index.test.tsx
  services/ui-src/src/components/IETRate/index.tsx
  services/ui-src/src/components/index.tsx
  services/ui-src/src/measures/2023/IETAD/index.tsx
  services/ui-src/src/measures/2023/IETHH/index.tsx
  services/ui-src/src/measures/2023/shared/CommonQuestions/PerformanceMeasure/index.tsx
Labels: ready for review
