Repository Enterprise-CMCS/macpro-mdct-qmr, pull requests merged in 2024-07, with the labels that each got.

#2300 FFY 24 MSC AD
  services/ui-src/src/measures/2024/MSCAD/index.test.tsx
  services/ui-src/src/measures/2024/MSCAD/index.tsx
  services/ui-src/src/measures/2024/MSCAD/questions/HowDidYouReport.tsx
  services/ui-src/src/measures/2024/MSCAD/questions/Reporting.tsx
  services/ui-src/src/measures/2024/MSCAD/questions/index.tsx
  services/ui-src/src/measures/2024/MSCAD/types.ts
  services/ui-src/src/measures/2024/MSCAD/validation.ts
Labels: ready for review

#2303 Migrate type from String[] to LabelData[] (2022)
  services/ui-src/src/measures/2022/AMBHH/index.tsx
  services/ui-src/src/measures/2022/AMMAD/validation.ts
  services/ui-src/src/measures/2022/CBPAD/validation.ts
  services/ui-src/src/measures/2022/CBPHH/index.tsx
  services/ui-src/src/measures/2022/CBPHH/validation.ts
  services/ui-src/src/measures/2022/CCWAD/validation.ts
  services/ui-src/src/measures/2022/FUHHH/index.tsx
  services/ui-src/src/measures/2022/HPCMIAD/validation.ts
  services/ui-src/src/measures/2022/IETAD/validation.ts
  services/ui-src/src/measures/2022/IETHH/validation.ts
  services/ui-src/src/measures/2022/OEVCH/index.tsx
  services/ui-src/src/measures/2022/PCRAD/questions/PerformanceMeasure.tsx
  services/ui-src/src/measures/2022/PCRHH/questions/PerformanceMeasure.tsx
  services/ui-src/src/measures/2022/PQI05AD/validation.ts
  services/ui-src/src/measures/2022/PQI92HH/index.tsx
  services/ui-src/src/measures/2022/WCCCH/data.ts
  services/ui-src/src/measures/2022/rateLabelText.test.ts
  services/ui-src/src/measures/2022/rateLabelText.ts
  services/ui-src/src/measures/2022/shared/CommonQuestions/PerformanceMeasure/data.ts
  services/ui-src/src/measures/2022/shared/CommonQuestions/PerformanceMeasure/index.test.tsx
  services/ui-src/src/measures/2022/shared/CommonQuestions/PerformanceMeasure/index.tsx
  services/ui-src/src/measures/2022/shared/CommonQuestions/types.ts
  services/ui-src/src/measures/2022/shared/globalValidations/ComplexValidations/ComplexValidateNDRTotals/index.tsx
  services/ui-src/src/measures/2022/shared/globalValidations/ComplexValidations/ComplexValueSameCrossCategory/index.tsx
  services/ui-src/src/measures/2022/shared/globalValidations/PCRValidations/PCRatLeastOneRateComplete/index.tsx
  services/ui-src/src/measures/2022/shared/globalValidations/dataDrivenTools.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/dataDrivenTools.ts
  services/ui-src/src/measures/2022/shared/globalValidations/omsValidator/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/omsValidator/index.ts
  services/ui-src/src/measures/2022/shared/globalValidations/types.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateAtLeastOneDeviationFieldFilled/index.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateAtLeastOneRateComplete/index.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateDualPopInformation/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateEqualCategoryDenominators/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateEqualCategoryDenominators/index.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateEqualQualifierDenominators/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateEqualQualifierDenominators/index.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateNoNonZeroNumOrDenom/index.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateNumeratorsLessThanDenominators/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateNumeratorsLessThanDenominators/index.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateOneCatRateHigherThanOtherCat/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateOneCatRateHigherThanOtherCat/index.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateOneQualDenomHigherThanOtherDenomOMS/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateOneQualDenomHigherThanOtherDenomOMS/index.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateOneQualRateHigherThanOtherQual/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateOneQualRateHigherThanOtherQual/index.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validatePartialRateCompletion/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validatePartialRateCompletion/index.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateRateNotZero/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateRateNotZero/index.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateRateZero/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateRateZero/index.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateTotals/index.test.tsx
  services/ui-src/src/measures/2022/shared/globalValidations/validateTotals/index.ts
  services/ui-src/src/measures/2023/shared/globalValidations/validateDualPopInformation/index.test.ts
  services/ui-src/src/measures/2024/shared/globalValidations/validateDualPopInformation/index.test.ts
  services/ui-src/src/utils/testUtils/validationHelpers.ts
Labels: ready for review

#2307 move deploy to run
  .github/workflows/deploy.yml
  deploy.sh
  src/run.ts
Labels: ready for review

#2314 Inconsistent Rounding
  services/app-api/handlers/rate/calculations/rateCalculation.ts
  services/app-api/utils/constants/math.ts
Labels: ready for review

#2319 Combined Rates Page - Rates showing in wrong order
  services/ui-src/src/labels/RateTextLabels.tsx
  services/ui-src/src/shared/commonQuestions/CombinedRateNDR/CombinedRateNDR.tsx
  services/ui-src/src/utils/testUtils/useApiMock.tsx
  services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.test.tsx
  services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.tsx
Labels: ready for review, product review

#2320 Combined Rates Page - Strict check & Not Reporting Behavior
  services/app-api/handlers/rate/calculations/adminstrativeCalculation.ts
  services/app-api/handlers/rate/calculations/types.ts
  services/app-api/handlers/rate/shared/calculateAndPutRate.ts
  services/app-api/test-util/testData.ts
Labels: product review

#2311 QMR - IET-AD validation for totals matching sum
  services/ui-src/src/measures/2024/IETAD/validation.ts
  services/ui-src/src/measures/2024/shared/CommonQuestions/types.ts
  services/ui-src/src/measures/2024/shared/globalValidations/index.ts
  services/ui-src/src/measures/2024/shared/globalValidations/types.ts
  services/ui-src/src/measures/2024/shared/globalValidations/validateNDRTotalsMatchSum/index.test.ts
  services/ui-src/src/measures/2024/shared/globalValidations/validateNDRTotalsMatchSum/index.ts
  services/ui-src/src/measures/2024/shared/globalValidations/validateNDRTotalsMatchSum/validationHelpers.ts
Labels: product review

#2326 '21 and '22 OPM data is incorrect
  services/ui-src/src/shared/commonQuestions/OptionalMeasureStrat/NDR/ndrCheckboxes.tsx
  services/ui-src/src/shared/commonQuestions/OptionalMeasureStrat/context.ts
  services/ui-src/src/shared/commonQuestions/OptionalMeasureStrat/omsUtil.tsx
  services/ui-src/src/shared/types/TypeCategories.tsx
  services/ui-src/src/shared/types/TypeQualifiers.tsx
Labels: ready for review

#2346 Banner - Adult Core Set
  services/ui-src/src/views/CoreSet/index.tsx
Labels: ready for review

#2350 Clean Up: Label to Id Migration Garbage
  services/ui-src/src/labels/RateLabelTexts.tsx
  services/ui-src/src/labels/rateLabelText.test.ts
  services/ui-src/src/measures/2021/rateLabelText.ts
  services/ui-src/src/measures/2022/rateLabelText.test.ts
  services/ui-src/src/measures/2023/rateLabelText.test.ts
  services/ui-src/src/measures/2024/rateLabelText.test.ts
  services/ui-src/src/shared/commonQuestions/CombinedRateNDR/CombinedRateNDR.tsx
  services/ui-src/src/shared/commonQuestions/DeviationFromMeasureSpecificationCheckboxes.tsx
  services/ui-src/src/shared/commonQuestions/OptionalMeasureStrat/NDR/ndrCheckboxes.tsx
  services/ui-src/src/shared/commonQuestions/OptionalMeasureStrat/NDR/ndrSets.tsx
  services/ui-src/src/shared/commonQuestions/OptionalMeasureStrat/NDR/rates.tsx
  services/ui-src/src/shared/commonQuestions/OptionalMeasureStrat/NDR/totalNDRSets.tsx
  services/ui-src/src/utils/getLabelText.tsx
Labels: ready for review

#2348 Clean Up: Validation helper
  services/ui-src/src/measures/2021/globalValidations/dataDrivenTools.test.ts
  services/ui-src/src/measures/2021/globalValidations/omsValidator/index.test.ts
  services/ui-src/src/measures/2021/globalValidations/validateDualPopInformation/index.test.ts
  services/ui-src/src/measures/2021/globalValidations/validateEqualCategoryDenominators/index.test.ts
  services/ui-src/src/measures/2021/globalValidations/validateEqualQualifierDenominators/index.test.ts
  services/ui-src/src/measures/2021/globalValidations/validateNumeratorsLessThanDenominators/index.test.ts
  services/ui-src/src/measures/2021/globalValidations/validateOneCatRateHigherThanOtherCat/index.test.ts
  services/ui-src/src/measures/2021/globalValidations/validateOneQualDenomHigherThanOtherDenomOMS/index.test.ts
  services/ui-src/src/measures/2021/globalValidations/validateOneQualRateHigherThanOtherQual/index.test.ts
  services/ui-src/src/measures/2021/globalValidations/validatePartialRateCompletion/index.test.ts
  services/ui-src/src/measures/2021/globalValidations/validateRateNotZero/index.test.ts
  services/ui-src/src/measures/2021/globalValidations/validateRateZero/index.test.ts
  services/ui-src/src/measures/2021/globalValidations/validateTotals/index.test.tsx
  services/ui-src/src/measures/2022/shared/globalValidations/dataDrivenTools.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/omsValidator/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateDualPopInformation/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateEqualCategoryDenominators/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateEqualQualifierDenominators/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateNumeratorsLessThanDenominators/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateOneCatRateHigherThanOtherCat/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateOneQualDenomHigherThanOtherDenomOMS/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateOneQualRateHigherThanOtherQual/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validatePartialRateCompletion/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateRateNotZero/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateRateZero/index.test.ts
  services/ui-src/src/measures/2022/shared/globalValidations/validateTotals/index.test.tsx
  services/ui-src/src/measures/2023/shared/globalValidations/dataDrivenTools.test.ts
  services/ui-src/src/measures/2023/shared/globalValidations/omsValidator/index.test.ts
  services/ui-src/src/measures/2023/shared/globalValidations/validateDualPopInformation/index.test.ts
  services/ui-src/src/measures/2023/shared/globalValidations/validateEqualCategoryDenominators/index.test.ts
  services/ui-src/src/measures/2023/shared/globalValidations/validateEqualQualifierDenominators/index.test.ts
  services/ui-src/src/measures/2023/shared/globalValidations/validateNumeratorsLessThanDenominators/index.test.ts
  services/ui-src/src/measures/2023/shared/globalValidations/validateOneCatRateHigherThanOtherCat/index.test.ts
  services/ui-src/src/measures/2023/shared/globalValidations/validateOneQualDenomHigherThanOtherDenomOMS/index.test.ts
  services/ui-src/src/measures/2023/shared/globalValidations/validateOneQualRateHigherThanOtherQual/index.test.ts
  services/ui-src/src/measures/2023/shared/globalValidations/validatePartialRateCompletion/index.test.ts
  services/ui-src/src/measures/2023/shared/globalValidations/validateRateNotZero/index.test.ts
  services/ui-src/src/measures/2023/shared/globalValidations/validateRateZero/index.test.ts
  services/ui-src/src/measures/2023/shared/globalValidations/validateSameDenominatorSets/index.test.ts
  services/ui-src/src/measures/2023/shared/globalValidations/validateTotals/index.test.tsx
  services/ui-src/src/measures/2024/shared/globalValidations/dataDrivenTools.test.ts
  services/ui-src/src/measures/2024/shared/globalValidations/omsValidator/index.test.ts
  services/ui-src/src/measures/2024/shared/globalValidations/validateDualPopInformation/index.test.ts
  services/ui-src/src/measures/2024/shared/globalValidations/validateEqualCategoryDenominators/index.test.ts
  services/ui-src/src/measures/2024/shared/globalValidations/validateEqualQualifierDenominators/index.test.ts
  services/ui-src/src/measures/2024/shared/globalValidations/validateNumeratorsLessThanDenominators/index.test.ts
  services/ui-src/src/measures/2024/shared/globalValidations/validateOneCatRateHigherThanOtherCat/index.test.ts
  services/ui-src/src/measures/2024/shared/globalValidations/validateOneQualDenomHigherThanOtherDenomOMS/index.test.ts
  services/ui-src/src/measures/2024/shared/globalValidations/validateOneQualRateHigherThanOtherQual/index.test.ts
  services/ui-src/src/measures/2024/shared/globalValidations/validatePartialRateCompletion/index.test.ts
  services/ui-src/src/measures/2024/shared/globalValidations/validateRateNotZero/index.test.ts
  services/ui-src/src/measures/2024/shared/globalValidations/validateRateZero/index.test.ts
  services/ui-src/src/measures/2024/shared/globalValidations/validateSameDenominatorSets/index.test.ts
  services/ui-src/src/measures/2024/shared/globalValidations/validateTotals/index.test.tsx
  services/ui-src/src/utils/testUtils/2023/validationHelper.test.ts
  services/ui-src/src/utils/testUtils/2023/validationHelpers.ts
  services/ui-src/src/utils/testUtils/2024/validationHelper.test.ts
  services/ui-src/src/utils/testUtils/2024/validationHelpers.ts
  services/ui-src/src/utils/testUtils/validationHelper.test.ts
  services/ui-src/src/utils/testUtils/validationHelpers.ts
Labels: ready for review

#2343 Combine Rates - Hybrid Data Source Only
  services/app-api/handlers/rate/calculations/adminstrativeCalculation.test.ts
  services/app-api/handlers/rate/calculations/adminstrativeCalculation.ts
  services/app-api/handlers/rate/calculations/hybridCalculation.test.ts
  services/app-api/handlers/rate/calculations/hybridCalculation.ts
  services/app-api/handlers/rate/calculations/index.ts
  services/app-api/handlers/rate/calculations/rateCalculation.ts
  services/app-api/handlers/rate/calculations/types.ts
  services/app-api/handlers/rate/shared/calculateAndPutRate.ts
  services/app-api/test-util/testData.ts
  services/app-api/types.ts
  services/ui-src/src/shared/commonQuestions/CombinedRateNDR/CombinedRateNDR.tsx
  services/ui-src/src/shared/commonQuestions/CombinedRateNDR/CombinedRateTypes.ts
  services/ui-src/src/shared/commonQuestions/DataSouceInformationBanner/DataSourceInformationBanner.tsx
Labels: ready for review

#2345 ComplexNoNonZeroNumOrDenom Validation - Incorrect Label
  services/ui-src/src/measures/2021/AIFHH/validation.ts
  services/ui-src/src/measures/2021/IUHH/validation.ts
  services/ui-src/src/measures/2021/globalValidations/ComplexValidations/ComplexNoNonZeroNumOrDenom/index.tsx
  services/ui-src/src/measures/2022/AIFHH/validation.ts
  services/ui-src/src/measures/2022/IUHH/validation.ts
  services/ui-src/src/measures/2022/shared/globalValidations/ComplexValidations/ComplexNoNonZeroNumOrDenom/index.tsx
  services/ui-src/src/measures/2023/AIFHH/validation.ts
  services/ui-src/src/measures/2023/IUHH/validation.ts
  services/ui-src/src/measures/2023/shared/globalValidations/ComplexValidations/ComplexNoNonZeroNumOrDenom/index.tsx
  services/ui-src/src/measures/2024/AIFHH/validation.ts
  services/ui-src/src/measures/2024/IUHH/validation.ts
  services/ui-src/src/measures/2024/shared/globalValidations/ComplexValidations/ComplexNoNonZeroNumOrDenom/index.tsx
Labels: ready for review

#2330 Consolidate CommonQuestions - PerformanceMeasure
  services/ui-src/src/components/ComplexRate/index.test.tsx
  services/ui-src/src/components/ComplexRate/index.tsx
  services/ui-src/src/measures/2021/AIFHH/data.ts
  services/ui-src/src/measures/2021/CommonQuestions/PerformanceMeasure/data.ts
  services/ui-src/src/measures/2021/CommonQuestions/PerformanceMeasure/index.test.tsx
  services/ui-src/src/measures/2021/CommonQuestions/PerformanceMeasure/index.tsx
  services/ui-src/src/measures/2021/CommonQuestions/index.tsx
  services/ui-src/src/measures/2021/CommonQuestions/types.ts
  services/ui-src/src/measures/2021/IUHH/data.ts
  services/ui-src/src/measures/2021/PCRAD/questions/PerformanceMeasure.tsx
  services/ui-src/src/measures/2021/PCRHH/questions/PerformanceMeasure.tsx
  services/ui-src/src/measures/2021/globalValidations/testHelpers/_helper.ts
  services/ui-src/src/measures/2021/globalValidations/types.ts
  services/ui-src/src/measures/2022/AIFHH/data.ts
  services/ui-src/src/measures/2022/IUHH/data.ts
  services/ui-src/src/measures/2022/PCRAD/questions/PerformanceMeasure.tsx
  services/ui-src/src/measures/2022/PCRHH/questions/PerformanceMeasure.tsx
  services/ui-src/src/measures/2022/shared/CommonQuestions/PerformanceMeasure/data.ts
  services/ui-src/src/measures/2022/shared/CommonQuestions/PerformanceMeasure/index.test.tsx
  services/ui-src/src/measures/2022/shared/CommonQuestions/PerformanceMeasure/index.tsx
  services/ui-src/src/measures/2022/shared/CommonQuestions/index.tsx
  services/ui-src/src/measures/2022/shared/CommonQuestions/types.ts
  services/ui-src/src/measures/2022/shared/globalValidations/testHelpers/_helper.ts
  services/ui-src/src/measures/2022/shared/globalValidations/types.ts
  services/ui-src/src/measures/2023/PCRAD/questions/PerformanceMeasure.tsx
  services/ui-src/src/measures/2023/PCRHH/questions/PerformanceMeasure.tsx
  services/ui-src/src/measures/2023/shared/CommonQuestions/PerformanceMeasure/data.ts
  services/ui-src/src/measures/2023/shared/CommonQuestions/PerformanceMeasure/index.test.tsx
  services/ui-src/src/measures/2023/shared/CommonQuestions/index.ts
  services/ui-src/src/measures/2023/shared/CommonQuestions/types.ts
  services/ui-src/src/measures/2023/shared/globalValidations/testHelpers/_helper.ts
  services/ui-src/src/measures/2023/shared/globalValidations/types.ts
  services/ui-src/src/measures/2024/PCRAD/questions/PerformanceMeasure.tsx
  services/ui-src/src/measures/2024/PCRHH/questions/PerformanceMeasure.tsx
  services/ui-src/src/measures/2024/shared/CommonQuestions/PerformanceMeasure/index.tsx
  services/ui-src/src/measures/2024/shared/CommonQuestions/index.ts
  services/ui-src/src/measures/2024/shared/CommonQuestions/types.ts
  services/ui-src/src/measures/2024/shared/globalValidations/testHelpers/_helper.ts
  services/ui-src/src/shared/commonQuestions/OptionalMeasureStrat/context.ts
  services/ui-src/src/shared/commonQuestions/OptionalMeasureStrat/index.tsx
  services/ui-src/src/shared/commonQuestions/PerformanceMeasure/data.ts
  services/ui-src/src/shared/commonQuestions/PerformanceMeasure/index.test.tsx
  services/ui-src/src/shared/commonQuestions/PerformanceMeasure/index.tsx
  services/ui-src/src/shared/types/TypePerformanceMeasure.tsx
  services/ui-src/src/shared/types/TypeRateFields.tsx
Labels: ready for review

#2353 Hybrid & Another Data Source Calculation
  services/app-api/handlers/rate/calculations/adminstrativeCalculation.ts
  services/app-api/handlers/rate/calculations/hybridCalculation.ts
  services/app-api/handlers/rate/calculations/hybridOtherCalculation.test.ts
  services/app-api/handlers/rate/calculations/hybridOtherCalculation.ts
  services/app-api/handlers/rate/calculations/index.ts
  services/app-api/handlers/rate/calculations/rateCalculation.ts
  services/app-api/handlers/rate/shared/calculateAndPutRate.ts
  services/ui-src/src/shared/commonQuestions/CombinedRateNDR/CombinedRateNDR.tsx
Labels: ready for review

#2351 CMDCT-3854: Adding mandatory column to 2024 measures table
  services/app-api/handlers/dynamoUtils/measureList.ts
  services/app-api/handlers/measures/get.ts
  services/app-api/types.ts
  services/ui-src/src/components/Table/columns/measures.tsx
  services/ui-src/src/components/Table/types.ts
  services/ui-src/src/types.ts
  services/ui-src/src/views/CoreSet/index.tsx
Labels: ready for review

#2352 CMDCT-3644, CMDCT-3879: updating qualifier content for separate chip and medicaid
  services/ui-src/src/measures/2024/shared/Qualifiers/data.ts
Labels: ready for review

#2355 Core Set Order - Home page
  services/ui-src/src/views/StateHome/index.tsx
  tests/cypress/cypress/e2e/userflow_child.spec.ts
Labels: ready for review
