Repository Enterprise-CMCS/macpro-mdct-qmr, pull requests merged in 2024-06, with the labels that each got.

#2259 Combined Rates Landing Page
  services/ui-src/src/Routes.tsx
  services/ui-src/src/components/Table/index.tsx
  services/ui-src/src/hooks/api/useGetMeasures.tsx
  services/ui-src/src/theme.ts
  services/ui-src/src/types.ts
  services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.test.tsx
  services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.tsx
  services/ui-src/src/views/CombinedRatesPage/index.test.tsx
  services/ui-src/src/views/CombinedRatesPage/index.tsx
  services/ui-src/src/views/CoreSet/index.tsx
  services/ui-src/src/views/index.tsx
Labels: ready for review

#2244 Add Measurement Specification Description Verbiage
  services/ui-src/src/labels/2024/commonQuestionsLabel.tsx
  services/ui-src/src/shared/commonQuestions/MeasurementSpecification.tsx
Labels: ready for review

#2272 [QMR] CPU-AD Rate Name Validation
  services/ui-src/src/measures/2024/CPUAD/validation.ts
Labels: ready for review

#2268 [QMR] Combined Rates Measurement Page - Initial
  services/ui-src/src/Routes.tsx
  services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.test.tsx
  services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.tsx
Labels: ready for review

#2264 Combine Rates - Administrative Data Source Only Calculation
  .env.tpl
  serverless-compose.yml
  services/app-api/handlers/measures/update.ts
  services/app-api/handlers/rate/calculations/adminstrativeCalculation.test.ts
  services/app-api/handlers/rate/calculations/adminstrativeCalculation.ts
  services/app-api/handlers/rate/calculations/index.ts
  services/app-api/handlers/rate/calculations/rateCalculation.ts
  services/app-api/handlers/rate/calculations/types.ts
  services/app-api/handlers/rate/get.ts
  services/app-api/handlers/rate/shared/calculateAndPutRate.test.ts
  services/app-api/handlers/rate/shared/calculateAndPutRate.ts
  services/app-api/handlers/rate/tests/get.test.ts
  services/app-api/package.json
  services/app-api/serverless.yml
  services/app-api/storage/table.test.ts
  services/app-api/storage/table.ts
  services/app-api/test-util/testData.ts
  services/app-api/types.ts
  services/database/serverless.yml
  services/ui-src/setupJest.ts
  services/ui-src/src/hooks/api/index.tsx
  services/ui-src/src/hooks/api/useGetRate.tsx
  services/ui-src/src/libs/api.ts
  services/ui-src/src/utils/testUtils/useApiMock.tsx
  services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.test.tsx
  services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.tsx
  services/uploads/serverless.yml
Labels: draft

#2284 Health Home Landing Page Undefined label
  services/ui-src/src/views/CoreSet/index.tsx
Labels: ready for review

#2283 3648 Data Source Information Banner
  services/ui-src/src/shared/commonQuestions/DataSouceInformationBanner/DataSourceInformationBanner.tsx
  services/ui-src/src/shared/commonQuestions/DataSouceInformationBanner/combinedRates.json
  services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.test.tsx
  services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.tsx
Labels: ready for review, design review

#2282 remove unit test branch lock
  .github/workflows/deploy.yml
  .github/workflows/unittest-workflow.yml
Labels: ready for review

#2296 Combined Rates - Data Source Nested Textboxes Info
  services/ui-src/src/measures/2024/CPCCH/index.test.tsx
  services/ui-src/src/shared/commonQuestions/DataSouceInformationBanner/DataSourceInformationBanner.test.tsx
  services/ui-src/src/shared/commonQuestions/DataSouceInformationBanner/DataSourceInformationBanner.tsx
  services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.tsx
Labels: ready for review

#2299 Combined Rates - Mobile Combine Rates Table
  services/ui-src/src/shared/commonQuestions/CombinedRateNDR/CombinedRateNDR.tsx
  services/ui-src/src/theme.ts
Labels: ready for review

#2295 Cmdct CPA-AD
  services/ui-src/src/measures/2024/CPAAD/index.test.tsx
  services/ui-src/src/measures/2024/CPAAD/index.tsx
  services/ui-src/src/measures/2024/CPAAD/questions/DataSource.tsx
  services/ui-src/src/measures/2024/CPAAD/questions/DefinitionOfPopulation.tsx
  services/ui-src/src/measures/2024/CPAAD/questions/HowDidYouReport.tsx
  services/ui-src/src/measures/2024/CPCCH/index.test.tsx
  services/ui-src/src/measures/2024/MSCAD/index.test.tsx
Labels: ready for review
