Repository Enterprise-CMCS/macpro-mdct-qmr, pull requests merged in 2024-05, with the labels that each got.

#2197 Implement serverless compose
  .env_example
  deploy.sh
  package.json
  plugins/serverless-iam-helper/.gitignore
  plugins/serverless-iam-helper/README.md
  plugins/serverless-iam-helper/index.js
  plugins/serverless-iam-helper/package.json
  plugins/serverless-idempotency-helper/.gitignore
  plugins/serverless-idempotency-helper/README.md
  plugins/serverless-idempotency-helper/index.js
  plugins/serverless-idempotency-helper/package.json
  plugins/serverless-s3-bucket-helper/.gitignore
  plugins/serverless-s3-bucket-helper/README.md
  plugins/serverless-s3-bucket-helper/index.js
  plugins/serverless-s3-bucket-helper/package.json
  serverless-compose.yml
  services/app-api/package.json
  services/app-api/serverless.yml
  services/app-api/yarn.lock
  services/database/package.json
  services/database/yarn.lock
  services/ui-auth/package.json
  services/ui-auth/serverless.yml
  services/ui-auth/yarn.lock
  services/ui-src/package.json
  services/ui-src/serverless.yml
  services/ui-src/yarn.lock
  services/ui/package.json
  services/ui/yarn.lock
  services/uploads/package.json
  services/uploads/serverless.yml
  services/uploads/yarn.lock
  yarn.lock
Labels: ready for review

#2205 Bump action versions
  .github/workflows/audit-account.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/cypress-workflow.yml
  .github/workflows/deploy.yml
  .github/workflows/pullrequest-precommit-check.yml
  .github/workflows/unittest-workflow.yml
Labels: ready for review

#2208 AAB-AD 2024 content change
  services/ui-src/src/measures/2024/AABAD/data.ts
Labels: ready for review

#2213 Add word 'reporting' to autocompleted measure template
  services/ui-src/src/components/AutocompletedMeasureTemplate/index.tsx
Labels: ready for review

#2212 Add "View Combined Rates" button to state home page
  services/ui-src/src/Routes.tsx
  services/ui-src/src/views/CombinedRatesPage/index.test.tsx
  services/ui-src/src/views/CombinedRatesPage/index.tsx
  services/ui-src/src/views/StateHome/__tests__/index.test.tsx
  services/ui-src/src/views/StateHome/index.tsx
  services/ui-src/src/views/index.tsx
Labels: ready for review

#2215 Change text in OUD-AD
  services/ui-src/src/measures/2024/OUDAD/data.ts
Labels: ready for review

#2216 Update additional notes text area label logic
  services/ui-src/src/labels/2021/commonQuestionsLabel.tsx
  services/ui-src/src/labels/2022/commonQuestionsLabel.tsx
  services/ui-src/src/labels/2023/commonQuestionsLabel.tsx
  services/ui-src/src/labels/2024/commonQuestionsLabel.tsx
  services/ui-src/src/shared/commonQuestions/AdditionalNotes.test.tsx
  services/ui-src/src/shared/commonQuestions/AdditionalNotes.tsx
Labels: ready for review, design review

#2217 All Measures - OMS Section Additional Field
  services/ui-src/src/dataConstants.ts
  services/ui-src/src/labels/2024/commonQuestionsLabel.tsx
  services/ui-src/src/shared/commonQuestions/OptionalMeasureStrat/index.tsx
  services/ui-src/src/shared/types/TypeOptionalMeasureStratification.tsx
Labels: ready for review

#2207 IETRate component fix for react hook upgrade
  services/ui-src/src/components/IETRate/index.test.tsx
  services/ui-src/src/components/IETRate/index.tsx
  services/ui-src/src/measures/2024/IETAD/data.ts
  services/ui-src/src/measures/2024/IETHH/data.ts
  services/ui-src/src/measures/2024/shared/CommonQuestions/PerformanceMeasure/index.tsx
Labels: ready for review

#2220 Forgot To Bring IETRate Changes to 2023
  services/ui-src/src/measures/2023/IETAD/data.ts
  services/ui-src/src/measures/2023/IETHH/data.ts
  services/ui-src/src/measures/2023/shared/CommonQuestions/PerformanceMeasure/index.tsx
Labels: ready for review

#2200 Cmdct 3449 - use reporting year and loaded prop to determine if the adult coreset should preload
  services/app-api/handlers/coreSets/get.ts
  services/app-api/handlers/coreSets/tests/get.test.ts
  services/app-api/libs/coreSetByYearPreloaded.ts
  services/ui-src/src/components/Table/index.tsx
  services/ui-src/src/views/StateHome/actions.ts
  services/ui-src/src/views/StateHome/index.tsx
  tests/cypress/cypress/e2e/userflow_admin.spec.ts
  tests/cypress/cypress/e2e/userflow_adult.spec.ts
  tests/cypress/helper.d.ts
  tests/cypress/support/commands.ts
Labels: ready for review

#2229 Cypress Dropdown Fix
  tests/cypress/cypress/e2e/userflow_adult.spec.ts
  tests/cypress/cypress/e2e/userflow_child.spec.ts
  tests/cypress/support/commands.ts
Labels: ready for review

#2224 Upgrade QMR to Node 20
  .github/workflows/cypress-workflow.yml
  .nvmrc
  package.json
  services/app-api/serverless.yml
  services/database/package.json
  services/database/serverless.yml
  services/database/yarn.lock
  services/ui-auth/serverless.yml
  services/ui-src/serverless.yml
  services/ui/serverless.yml
  services/uploads/package.json
  services/uploads/serverless.yml
  services/uploads/yarn.lock
  tests/cypress/package.json
  tests/cypress/yarn.lock
  yarn.lock
Labels: ready for review

#2228 QMR-3568 Add validation for HBD-AD
  services/ui-src/src/measures/2024/HBDAD/index.test.tsx
  services/ui-src/src/measures/2024/HBDAD/validation.ts
Labels: ready for review

#2234 Mobile Dashboard
  services/ui-src/public/footer/mdct-qmr-footer.svg
  services/ui-src/public/footer/mdct.png
  services/ui-src/src/components/Breadcrumbs/index.tsx
  services/ui-src/src/components/CompleteMeasureFooter/index.tsx
  services/ui-src/src/components/ComplexRate/index.tsx
  services/ui-src/src/components/Footer/index.tsx
  services/ui-src/src/components/Header/index.tsx
  services/ui-src/src/components/IETRate/index.tsx
  services/ui-src/src/components/KebabMenu/index.tsx
  services/ui-src/src/components/Layouts/StateLayout/index.tsx
  services/ui-src/src/components/MeasureButtons/index.tsx
  services/ui-src/src/components/MeasureWrapper/complete.tsx
  services/ui-src/src/components/PCRRate/index.tsx
  services/ui-src/src/components/PrintableMeasureWrapper/index.tsx
  services/ui-src/src/components/Rate/index.tsx
  services/ui-src/src/components/Table/columns/measures.tsx
  services/ui-src/src/components/Table/index.tsx
  services/ui-src/src/index.scss
  services/ui-src/src/measures/2024/shared/Qualifiers/Common/administrativeQuestions.tsx
  services/ui-src/src/measures/2024/shared/Qualifiers/Common/audit.tsx
  services/ui-src/src/measures/2024/shared/Qualifiers/Common/costSavingsData.tsx
  services/ui-src/src/measures/2024/shared/Qualifiers/Common/externalContractor.tsx
  services/ui-src/src/measures/2024/shared/Qualifiers/deliverySystems.tsx
  services/ui-src/src/measures/2024/shared/Qualifiers/index.tsx
  services/ui-src/src/theme.ts
  services/ui-src/src/views/CoreSet/index.tsx
  services/ui-src/src/views/ExportAll/index.tsx
  services/ui-src/src/views/StateHome/AddCoreSetCards.tsx
  services/ui-src/src/views/StateHome/index.tsx
Labels: ready for review

#2241 Fix DOM text reinterpreted as HTML
  services/ui-src/src/components/Banner/Banner.tsx
Labels: ready for review

#2236 Global Change Added language to Footer
  services/ui-src/src/components/SupportInfo/index.tsx
  tests/cypress/cypress/e2e/userflow_healthhome.spec.ts
Labels: ready for review, design review

#2237 Migrate to Vite from react-scripts
  services/ui-src/index.html
  services/ui-src/package.json
  services/ui-src/public/index.html
  services/ui-src/setupJest.ts
  services/ui-src/src/index.scss
  services/ui-src/src/serviceWorker.ts
  services/ui-src/src/utils/environmentVariables.ts
  services/ui-src/src/utils/getLabelText.tsx
  services/ui-src/src/utils/testUtils/styleMock.ts
  services/ui-src/tsconfig.json
  services/ui-src/vite-env.d.ts
  services/ui-src/vite.config.ts
  services/ui-src/yarn.lock
  tsconfig.json
Labels: do not merge

#2245 CPU-AD Update Performance Measure Text Formatting
  services/ui-src/src/index.scss
  services/ui-src/src/measures/2024/CPUAD/data.ts
  services/ui-src/src/measures/2024/CPUAD/questions/PerformanceMeasure.tsx
Labels: ready for review, design review

#2253 ECDS-Eligible measures - Warning Banner
  services/ui-src/src/labels/2024/commonQuestionsLabel.tsx
  services/ui-src/src/shared/commonQuestions/DataSource.tsx
  services/ui-src/src/shared/types/TypeDataSource.tsx
Labels: ready for review

#2256 Remove react scripts command
  services/ui-src/README.md
  services/ui-src/package.json
Labels: ready for review

#2252 PPC2-AD and PP2-CH Denom Validation
  services/ui-src/src/measures/2024/PPC2AD/validation.ts
  services/ui-src/src/measures/2024/PPC2CH/validation.ts
Labels: ready for review

#2251 Global Change - Performance Measure Missing Text Box
  services/ui-src/src/measures/2024/shared/CommonQuestions/PerformanceMeasure/index.tsx
Labels: ready for review

#2243 Timeout and save functionality
  services/ui-src/src/components/MeasureWrapper/index.test.tsx
  services/ui-src/src/components/MeasureWrapper/index.tsx
Labels: ready for review

#2258 [QMR] All Child and Adult Measures - In line warning banner (Measurement Specification)
  services/ui-src/src/labels/2024/commonQuestionsLabel.tsx
  services/ui-src/src/measures/2024/AABAD/index.tsx
  services/ui-src/src/measures/2024/AABCH/index.tsx
  services/ui-src/src/measures/2024/ADDCH/index.tsx
  services/ui-src/src/measures/2024/AMBCH/index.tsx
  services/ui-src/src/measures/2024/AMMAD/index.tsx
  services/ui-src/src/measures/2024/AMRAD/index.tsx
  services/ui-src/src/measures/2024/AMRCH/index.tsx
  services/ui-src/src/measures/2024/APMCH/index.tsx
  services/ui-src/src/measures/2024/APPCH/index.tsx
  services/ui-src/src/measures/2024/BCSAD/index.tsx
  services/ui-src/src/measures/2024/CBPAD/index.tsx
  services/ui-src/src/measures/2024/CCPAD/index.tsx
  services/ui-src/src/measures/2024/CCPCH/index.tsx
  services/ui-src/src/measures/2024/CCSAD/index.tsx
  services/ui-src/src/measures/2024/CCWAD/index.tsx
  services/ui-src/src/measures/2024/CCWCH/index.tsx
  services/ui-src/src/measures/2024/CDFAD/index.tsx
  services/ui-src/src/measures/2024/CDFCH/index.tsx
  services/ui-src/src/measures/2024/CHLAD/index.tsx
  services/ui-src/src/measures/2024/CHLCH/index.tsx
  services/ui-src/src/measures/2024/CISCH/index.tsx
  services/ui-src/src/measures/2024/COBAD/index.tsx
  services/ui-src/src/measures/2024/COLAD/index.tsx
  services/ui-src/src/measures/2024/CPAAD/index.tsx
  services/ui-src/src/measures/2024/CPCCH/index.tsx
  services/ui-src/src/measures/2024/CPUAD/index.tsx
  services/ui-src/src/measures/2024/DEVCH/index.tsx
  services/ui-src/src/measures/2024/FUAAD/index.tsx
  services/ui-src/src/measures/2024/FUACH/index.tsx
  services/ui-src/src/measures/2024/FUHAD/index.tsx
  services/ui-src/src/measures/2024/FUHCH/index.tsx
  services/ui-src/src/measures/2024/FUMAD/index.tsx
  services/ui-src/src/measures/2024/FUMCH/index.tsx
  services/ui-src/src/measures/2024/HBDAD/index.tsx
  services/ui-src/src/measures/2024/HPCMIAD/index.tsx
  services/ui-src/src/measures/2024/HVLAD/index.tsx
  services/ui-src/src/measures/2024/IETAD/index.tsx
  services/ui-src/src/measures/2024/IMACH/index.tsx
  services/ui-src/src/measures/2024/LSCCH/index.tsx
  services/ui-src/src/measures/2024/MSCAD/index.tsx
  services/ui-src/src/measures/2024/OEVCH/index.tsx
  services/ui-src/src/measures/2024/OHDAD/index.tsx
  services/ui-src/src/measures/2024/OUDAD/index.tsx
  services/ui-src/src/measures/2024/PCRAD/index.tsx
  services/ui-src/src/measures/2024/PPC2AD/index.tsx
  services/ui-src/src/measures/2024/PPC2CH/index.tsx
  services/ui-src/src/measures/2024/PQI01AD/index.tsx
  services/ui-src/src/measures/2024/PQI05AD/index.tsx
  services/ui-src/src/measures/2024/PQI08AD/index.tsx
  services/ui-src/src/measures/2024/PQI15AD/index.tsx
  services/ui-src/src/measures/2024/SAAAD/index.tsx
  services/ui-src/src/measures/2024/SFMCH/index.tsx
  services/ui-src/src/measures/2024/SSDAD/index.tsx
  services/ui-src/src/measures/2024/TFLCH/index.tsx
  services/ui-src/src/measures/2024/W30CH/index.tsx
  services/ui-src/src/measures/2024/WCCCH/index.tsx
  services/ui-src/src/measures/2024/WCVCH/index.tsx
  services/ui-src/src/shared/commonQuestions/MeasurementSpecification.tsx
Labels: ready for review
